### ISSUE TITLE
Failed to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by jschiefer** [phase4ground/ka9q-sdr#5]
In addition to the fftw3 issue in #2, Ubuntu 14.04 has the additional problem that one of the header files used (`stdatomic.h`) requires a gcc version > 4.9. Ubuntu 14.04 ships with gcc 4.8.

**Comment by ka9q** [comment]
On 6/22/18 01:38, Jan Schiefer wrote:
> In addition to the fftw3 issue in #2
> <https://github.com/phase4ground/ka9q-sdr/issues/2>, Ubuntu 14.04 has
> the additional problem that one of the header files used (|stdatomic.h|)
> requires a gcc version > 4.9. Ubuntu 14.04 ships with gcc 4.8.

Really? Seems pretty old. I run Debian Stable (stretch) on most of my
systems and it has gcc 6.3.0.

I do like to make my software as portable as possible, but there are
practical limits. Often the the newer version of something is the
"right" one to use in that it fixes some problem that is otherwise
difficult or impossible to fix.

Phil

**Comment by Abraxas3d** [comment]
Any progress on this? What can I do to help fix it?

**Comment by jschiefer** [comment]
Updating gcc is probably a non-starter. Maybe a workaround can be found, but as support for 14.04 is ending in April of 2019, I would suggest we focus our energy elsewhere. 
If we decide to not fix this, we need to update the README.md and INSTALL.md files to reflect this fact.

**Comment by ka9q** [comment]
What minimum version of Ubuntu is required to compile the package as it currently is? I'd like to add that to the documentation.

**Comment by ExplodingLemur** [comment]
Ubuntu 14.04 is end-of-support. Should this be closed?

**Comment by jschiefer** [comment]
Closing this as won't fix.
